In [1]:
import MotifCompendium

In [2]:
#mc = MotifCompendium.load("chrombpnet_outputs/motif_compendium_average.mc", safe=True)
mc = MotifCompendium.load("chrombpnet_outputs/motif_compendium.mc", safe=True)

In [3]:
import MotifCompendium.utils.analysis as utils_analysis

# reference_meme = '../pipeline/data/MotifCompendium-Database-Human.meme.txt'

# utils_analysis.assign_label_from_pfms(
#     mc,
#     reference_meme,
#     save_col_prefix="refdb",
#     min_score=0.5,
#     max_submotifs = 2
# )
# mc

In [4]:
utils_analysis.assign_label_from_pfms(
    mc,
    "chrombpnet_outputs/meme_invitro_avg.meme.txt",
    save_col_prefix="chiptf",
    min_score=0.5,
    max_submotifs = 2
)

In [5]:
print(f"Number of composite motifs: {(mc['chiptf_score1'] > 0).sum()}")

Number of composite motifs: 240

In [6]:
#mc
mc.save("chrombpnet_outputs/motif_compendium_annotated_new.mc")

In [7]:
print(f"Number of composite motifs: {(mc['chiptf_score0'] == 0).sum()}")

Number of composite motifs: 0

In [8]:
print(f"Number of composite motifs: {(mc['chiptf_score1'] == 0).sum()}")

Number of composite motifs: 591

In [9]:
print(f"Number of composite motifs: {(mc['refdb_score0'] == 0).sum()}")

Number of composite motifs: 0

In [10]:
print(f"Number of composite motifs: {(mc['refdb_score1'] == 0).sum()}")

Number of composite motifs: 640

In [11]:
sum((mc['refdb_score1']== 0) & (mc['chiptf_score0']==0))

0

In [12]:
mc[(mc['refdb_score1']== 0) & (mc['chiptf_score0']==0)]

In [ ]:
mc.columns

In [ ]:
import MotifCompendium.utils.motif as utils_motif

if "logo (fwd)" not in mc.images():
    mc.add_logos(mc.get_standard_motif_stack(), "logo (fwd)", True)
if "logo (rev)" not in mc.images():
    mc.add_logos(utils_motif.reverse_complement(mc.get_standard_motif_stack()), "logo (rev)", True)

In [ ]:
mc_pos = mc[mc["posneg"]=="pos"]
mc_neg = mc[mc["posneg"]=="neg"]

In [ ]:
mc_avg_pos = mc_pos.cluster_averages("cluster")
mc_avg_pos

In [ ]:
mc_avg_neg = mc_neg.cluster_averages("cluster")
mc_avg_neg

In [ ]:
reference_meme = '../pipeline/data/MotifCompendium-Database-Human.meme.txt'

utils_analysis.assign_label_from_pfms(
    mc_avg_pos,
    reference_meme,
    save_col_prefix="refdb",
    min_score=0.5,
    max_submotifs = 2
)

utils_analysis.assign_label_from_pfms(
    mc_avg_pos,
    "chrombpnet_outputs/meme_invitro_avg.meme.txt",
    save_col_prefix="chiptf",
    min_score=0.5,
    max_submotifs = 2
)

In [ ]:
reference_meme = '../pipeline/data/MotifCompendium-Database-Human.meme.txt'

utils_analysis.assign_label_from_pfms(
    mc_avg_neg,
    reference_meme,
    save_col_prefix="refdb",
    min_score=0.5,
    max_submotifs = 2
)

utils_analysis.assign_label_from_pfms(
    mc_avg_neg,
    "chrombpnet_outputs/meme_invitro_avg.meme.txt",
    save_col_prefix="chiptf",
    min_score=0.5,
    max_submotifs = 2
)

In [42]:
mc_avg_neg[(mc_avg_neg['refdb_score1']== 0) & (mc_avg_neg['chiptf_score0']==0)]

In [41]:
mc_avg_pos

In [43]:
MotifCompendium.set_compute_options(fast_plotting=True)

In [44]:
#mc_avg_pos.summary_table_html("chrombpnet_outputs/pos_cluster_summary_table.html")

In [45]:
#mc_avg_neg.summary_table_html("chrombpnet_outputs/neg_cluster_summary_table.html")

In [46]:
mc.save("chrombpnet_outputs/motif_compendium_annotated.mc")

In [65]:
sum((mc_avg_pos["refdb_score1"] > 0) & (mc_avg_pos["chiptf_score1"] > 0))

69

In [72]:
sum(mc_avg_pos["chiptf_score0"] > 0)

358

In [74]:
sum(mc_avg_pos["refdb_score0"] > 0)

358

In [75]:
sum(mc_avg_pos["refdb_score0"] > 0)

358

In [69]:
sum(mc_avg_neg["chiptf_score0"]>0)

25

In [70]:
mc_avg_neg