In [47]:
import MotifCompendium
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "1"

In [48]:
MotifCompendium.set_compute_options(max_cpus=4, progress_bar=True, max_chunk=1152, use_gpu=True)

In [49]:
maindir = "/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/ATAC/"
modisco_dict = {
    "GM12878_counts": maindir+"GM12878/merge_folds_new_may_05_24/counts/modisco_counts.h5",
    "GM12878_profile": maindir+"GM12878/merge_folds_new_may_05_24/profile/modisco_profile.h5",
    "K562_counts": maindir+"K562/merge_folds_new_may_05_24/counts/modisco_counts.h5",
    "K562_profile": maindir+"K562/merge_folds_new_may_05_24/profile/modisco_profile.h5",
     "HEPG2_counts": maindir+"HEPG2/merge_folds_new_may_05_24/counts/modisco_counts.h5",
    "HEPG2_profile": maindir+"HEPG2/merge_folds_new_may_05_24/profile/modisco_profile.h5",
     "IMR90_counts": maindir+"IMR90/merge_folds_new_may_05_24/counts/modisco_counts.h5",
    "IMR90_profile": maindir+"IMR90/merge_folds_new_may_05_24/profile/modisco_profile.h5",
     "H1ESC_counts": maindir+"H1ESC/merge_folds_new_may_05_24/counts/modisco_counts.h5",
    "H1ESC_profile": maindir+"H1ESC/merge_folds_new_may_05_24/profile/modisco_profile.h5",
    
}
mc = MotifCompendium.build_from_modisco(modisco_dict, modisco_region_width=500)
mc

computing similarities on GPU...: 100%|███████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.30it/s]

In [52]:
mc.heatmap(show=True, label=True)

In [53]:
import MotifCompendium.utils.analysis as utils_analysis

In [54]:
utils_analysis.plot_similarity_distribution(
    mc, "chrombpnet_outputs/similarity_distribution.html"
)

In [65]:
mc.cluster(similarity_threshold=0.97)
mc

In [66]:
# len(set(mc['cluster']))
# 574 clusters

In [67]:
mc.sort(by="cluster").heatmap(show=True, label=True)

In [68]:
mc_avg = mc.cluster_averages("cluster")
mc_avg

computing similarities on GPU...: 100%|███████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.12it/s]

In [63]:
mc.motif_collection_html("chrombpnet_outputs/motif_collection.html", "cluster")

In [64]:
mc_avg = mc.cluster_averages("cluster")
mc_avg

computing similarities on GPU...: 100%|███████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 27.10it/s]

In [30]:
mc_avg.add_motif_strings()
mc_avg

In [31]:
mc_avg.summary_table_html("chrombpnet_outputs/cluster_summary_table.html")

In [45]:
output_path= "/oak/stanford/groups/akundaje/cmyun/motifcompendium/tfatlas/encode/pipeline/counts/pipeline_counts_intarget-0.88-meta0.88-rec-force0.92/motifcompendium_avg_filtered.mc"

mc_3 = MotifCompendium.load(output_path, safe=True)

In [46]:
mc_3

In [42]:
mc_2

In [40]:
utils_analysis.assign_label_from_other_compendium(
    assign_to_mc=mc_avg,
    assign_from_mc=mc_2,
    save_col_prefix="chiptf",
    min_score=0.7,
    max_submotifs = 2
)
mc_avg

computing similarities on GPU...: 100%|█████████████████████████████████████████████████████████████████| 29/29 [00:14<00:00,  2.04it/s]
computing similarities on GPU...: 100%|█████████████████████████████████████████████████████████████████| 29/29 [00:04<00:00,  7.24it/s]

In [32]:
mc.save("chrombpnet_outputs/motif_compendium.mc")
mc_avg.save("chrombpnet_outputs/motif_compendium_average.mc")