In [2]:
import numpy as np
import pandas as pd
import h5py
import pysam
import os
from modisco.visualization import viz_sequence
from modisco import util
from matplotlib import pyplot as plt
import pybedtools
from bs4 import BeautifulSoup

pd.options.display.max_rows = 500
pd.options.display.max_columns = 500

In [3]:
# mode="print"
# modisco_path = '/mnt/lab_data2/anusri/chrombpnet/results/print/ATAC_PE/ENCSR158XTU/chrombpnet_compare/ENCSR158XTU/auxiliary/interpret_subsample/old_modisco_results_profile_scores.h5'
# ppm_dir = 'pwms/'

# htmld="/mnt/lab_data2/anusri/chrombpnet/results/print/ATAC_PE/ENCSR158XTU/chrombpnet_compare/ENCSR158XTU/evaluation/modisco_profile/motifs.html"
# tomtom = pd.read_html(htmld)

# mode="gm12878_print"
# modisco_path = '/mnt/lab_data2/anusri/chrombpnet/results/print/ATAC_PE/GM12878/ATAC_PE_05.08.2025_print_with_bias_bigwig/print_model/interpret/profile/old_modisco_results_profile_scores.h5'
# ppm_dir = 'pwms/'

# htmld="/mnt/lab_data2/anusri/chrombpnet/results/print/ATAC_PE/GM12878/ATAC_PE_05.08.2025_print_with_bias_bigwig/print_model/interpret/profile/motifs.html"
# tomtom = pd.read_html(htmld)

mode="kero_print"
modisco_path = '/mnt/lab_data2/anusri/chrombpnet/results/print/ATAC_PE/ENCSR158XTU/ATAC_PE_05.09.2025_print_with_bias_bigwig/print_model/interpret_new/profile/old_modisco_profile.h5'
ppm_dir = 'pwms/'

htmld="/mnt/lab_data2/anusri/chrombpnet/results/print/ATAC_PE/ENCSR158XTU/ATAC_PE_05.09.2025_print_with_bias_bigwig/print_model/interpret_new/profile/motifs.html"
tomtom = pd.read_html(htmld)

background=[0.25, 0.25, 0.25, 0.25]

In [4]:
def trim_motif_new(cwm, motif, trim_threshold=0.20):
    """
    Given the PFM and motif (both L x 4 arrays) (the motif could be the
    PFM itself), trims `motif` by cutting off flanks of low information
    content in `pfm`. `min_ic` is the minimum required information
    content. If specified this trimmed motif will be extended on either
    side by `pad` bases.
    If no base passes the `min_ic` threshold, then no trimming is done.
    """
    
    score = np.sum(np.abs(cwm), axis=1)
    trim_thresh = np.max(score) * trim_threshold  # Cut off anything less than 30% of max score
    pass_inds = np.where(score >= trim_thresh)[0]
    trimmed = motif[np.min(pass_inds): np.max(pass_inds) + 1]
 
    if not trimmed.size:
        return motif
    
    return trimmed

def import_tfmodisco_motifs(tfm_results_path, trim=True, only_pos=True):
    """
    Imports the PFMs to into a dictionary, mapping `(x, y)` to the PFM,
    where `x` is the metacluster index and `y` is the pattern index.
    Arguments:
        `tfm_results_path`: path to HDF5 containing TF-MoDISco results
        `out_dir`: where to save motifs
        `trim`: if True, trim the motif flanks based on information content
        `only_pos`: if True, only return motifs with positive contributions
    Returns the dictionary of PFMs.
    """ 
    pfms = {}
    with h5py.File(tfm_results_path, "r") as f:
        metaclusters = f["metacluster_idx_to_submetacluster_results"]
        num_metaclusters = len(metaclusters.keys())
        for metacluster_i, metacluster_key in enumerate(metaclusters.keys()):
            metacluster = metaclusters[metacluster_key]
            if "patterns" not in metacluster["seqlets_to_patterns_result"]:
                continue
            patterns = metacluster["seqlets_to_patterns_result"]["patterns"]
            num_patterns = len(patterns["all_pattern_names"][:])
            for pattern_i, pattern_name in enumerate(patterns["all_pattern_names"][:]):
#                pattern_name = pattern_name.decode()
                pattern_name = pattern_name

                pattern = patterns[pattern_name]
                pfm = pattern["sequence"]["fwd"][:]
                cwm = pattern["task0_contrib_scores"]["fwd"][:]
                
                # Check that the contribution scores are overall positive
                if only_pos and np.sum(cwm) < 0:
                    continue
                    
                if trim:
                    pfm = trim_motif_new(cwm, cwm)
                else:
                    pfm = cwm
                    
                pfms["%d_%d" % (metacluster_i,pattern_i)] = pfm
    return pfms

In [5]:
pfms = import_tfmodisco_motifs(modisco_path, trim=False)

In [6]:
for key in pfms:
    f = open(os.path.join(ppm_dir,mode+"_"+key+".pfm"),"w")
    #print(pfms[key])
    np.savetxt(f, pfms[key], fmt='%f')
    f.close()

In [7]:
tomtom[0]

,pattern,num_seqlets,modisco_cwm_fwd,modisco_cwm_rev,match0,qval0,match0_logo,match1,qval1,match1_logo,match2,qval2,match2_logo
0,pos_patterns.pattern_0,10413,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,pos_patterns.pattern_1,7966,NaN,NaN,FOSB_HUMAN.H11MO.0.A,1.020140e-04,NaN,FOSB_MOUSE.H11MO.0.A,1.020140e-04,NaN,JUN_HUMAN.H11MO.0.A,1.020140e-04,NaN
2,pos_patterns.pattern_2,2410,NaN,NaN,CTCF_MA0139.1,3.366060e-14,NaN,CTCF_HUMAN.H11MO.0.A,2.421640e-11,NaN,CTCF_MOUSE.H11MO.0.A,1.834120e-09,NaN
3,pos_patterns.pattern_3,1571,NaN,NaN,P73_HUMAN.H11MO.0.A,2.794620e-10,NaN,P73_MOUSE.H11MO.0.B,2.794620e-10,NaN,P63_HUMAN.H11MO.0.A,2.831130e-09,NaN
4,pos_patterns.pattern_4,681,NaN,NaN,KLF4_HUMAN.H11MO.0.A,4.082750e-06,NaN,KLF4_MOUSE.H11MO.0.A,1.793100e-05,NaN,KLF1_MOUSE.H11MO.0.A,1.829890e-05,NaN
5,pos_patterns.pattern_5,504,NaN,NaN,GRHL2_MA1105.1,4.192730e-05,NaN,GRHL2_MOUSE.H11MO.0.A,4.755160e-05,NaN,GRHL2_HUMAN.H11MO.0.A,4.895840e-05,NaN
6,pos_patterns.pattern_6,423,NaN,NaN,CEBPA_MA0102.3,5.820970e-08,NaN,CEBPB_HUMAN.H11MO.0.A,5.062910e-07,NaN,CEBPB_MOUSE.H11MO.0.A,6.118130e-06,NaN
7,pos_patterns.pattern_7,387,NaN,NaN,TFAP2A_MA0003.3,6.932970e-06,NaN,TFAP2A_TFAP_2,6.932970e-06,NaN,Tcfap2a.mouse_TFAP_2,1.153050e-05,NaN
8,pos_patterns.pattern_8,277,NaN,NaN,TEAD3_MA0808.1,1.118060e-02,NaN,TEAD3_TEA_2,1.118060e-02,NaN,FOSL2_MA0478.1,1.118060e-02,NaN
9,pos_patterns.pattern_9,263,NaN,NaN,TEAD3_MA0808.1,3.336740e-03,NaN,TEAD3_TEA_2,3.336740e-03,NaN,TEAD2_MOUSE.H11MO.0.C,3.759640e-02,NaN
10,pos_patterns.pattern_10,231,NaN,NaN,ATF2_HUMAN.H11MO.0.B,6.927430e-07,NaN,ATF2_MOUSE.H11MO.0.A,6.927430e-07,NaN,FOSL2+JUNB_MA1139.1,8.413850e-06,NaN
11,pos_patterns.pattern_11,167,NaN,NaN,PAX5_HUMAN.H11MO.0.A,8.396880e-01,NaN,FOS_HUMAN.H11MO.0.A,8.396880e-01,NaN,THA_HUMAN.H11MO.0.C,8.396880e-01,NaN
12,pos_patterns.pattern_12,115,NaN,NaN,KLF4_MA0039.3,1.054090e-02,NaN,SALL4_HUMAN.H11MO.0.B,2.713160e-01,NaN,SALL4_MOUSE.H11MO.0.A,2.713160e-01,NaN
13,pos_patterns.pattern_13,110,NaN,NaN,Tcfap2a.mouse_TFAP_1,1.826020e-03,NaN,TFAP2A_AP2_5,1.826020e-03,NaN,TFAP2C_MA0524.2,1.826020e-03,NaN
14,pos_patterns.pattern_14,104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,pos_patterns.pattern_15,74,NaN,NaN,ZN260_HUMAN.H11MO.0.C,2.489630e-02,NaN,OZF_HUMAN.H11MO.0.C,2.489630e-02,NaN,NFAC3_HUMAN.H11MO.0.B,1.000000e+00,NaN
16,pos_patterns.pattern_16,56,NaN,NaN,CEBPA_MA0102.3,3.542960e-02,NaN,CEBPB_HUMAN.H11MO.0.A,3.542960e-02,NaN,Atf4.mouse_bZIP_1,4.784110e-02,NaN
17,pos_patterns.pattern_17,50,NaN,NaN,FOS_HUMAN.H11MO.0.A,1.487240e-02,NaN,ATF3_MOUSE.H11MO.0.A,1.487240e-02,NaN,JUND_MOUSE.H11MO.0.A,1.487240e-02,NaN
18,pos_patterns.pattern_18,30,NaN,NaN,NFIC+TLX1_MA0119.1,4.388190e-02,NaN,NFIA_HUMAN.H11MO.0.C,1.016710e-01,NaN,NFIA_MOUSE.H11MO.0.C,1.016710e-01,NaN
19,pos_patterns.pattern_19,25,NaN,NaN,ZN121_HUMAN.H11MO.0.C,1.000000e+00,NaN,Pax2_MA0067.1,1.000000e+00,NaN,NFAC1_MOUSE.H11MO.0.A,1.000000e+00,NaN
20,pos_patterns.pattern_20,20,NaN,NaN,NRF1_MOUSE.H11MO.0.A,2.008650e-05,NaN,NRF1_NRF_1,2.008650e-05,NaN,NRF1_HUMAN.H11MO.0.A,3.143850e-05,NaN
21,neg_patterns.pattern_0,47,NaN,NaN,BACH1_HUMAN.H11MO.0.A,7.925380e-04,NaN,MAFF_MA0495.2,7.925380e-04,NaN,JDP2_MA0655.1,7.925380e-04,NaN
22,neg_patterns.pattern_1,45,NaN,NaN,ZBT7A_HUMAN.H11MO.0.A,9.690330e-02,NaN,ZBT7A_MOUSE.H11MO.0.B,9.690330e-02,NaN,SIX4_MOUSE.H11MO.0.C,9.690330e-02,NaN
23,neg_patterns.pattern_2,27,NaN,NaN,FOSL1+JUND_MA1142.1,3.354150e-04,NaN,FOSL1+JUNB_MA1137.1,3.354150e-04,NaN,FOSB+JUNB_MA1135.1,4.023170e-04,NaN

In [8]:

tomtom[0]["pattern"] = tomtom[0]["pattern"].str.replace("pos_patterns.pattern","0").str.replace("neg_patterns.pattern","1")

/users/anusri/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.

In [9]:
tomtom[0]

,pattern,num_seqlets,modisco_cwm_fwd,modisco_cwm_rev,match0,qval0,match0_logo,match1,qval1,match1_logo,match2,qval2,match2_logo
0,0_0,10413,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0_1,7966,NaN,NaN,FOSB_HUMAN.H11MO.0.A,1.020140e-04,NaN,FOSB_MOUSE.H11MO.0.A,1.020140e-04,NaN,JUN_HUMAN.H11MO.0.A,1.020140e-04,NaN
2,0_2,2410,NaN,NaN,CTCF_MA0139.1,3.366060e-14,NaN,CTCF_HUMAN.H11MO.0.A,2.421640e-11,NaN,CTCF_MOUSE.H11MO.0.A,1.834120e-09,NaN
3,0_3,1571,NaN,NaN,P73_HUMAN.H11MO.0.A,2.794620e-10,NaN,P73_MOUSE.H11MO.0.B,2.794620e-10,NaN,P63_HUMAN.H11MO.0.A,2.831130e-09,NaN
4,0_4,681,NaN,NaN,KLF4_HUMAN.H11MO.0.A,4.082750e-06,NaN,KLF4_MOUSE.H11MO.0.A,1.793100e-05,NaN,KLF1_MOUSE.H11MO.0.A,1.829890e-05,NaN
5,0_5,504,NaN,NaN,GRHL2_MA1105.1,4.192730e-05,NaN,GRHL2_MOUSE.H11MO.0.A,4.755160e-05,NaN,GRHL2_HUMAN.H11MO.0.A,4.895840e-05,NaN
6,0_6,423,NaN,NaN,CEBPA_MA0102.3,5.820970e-08,NaN,CEBPB_HUMAN.H11MO.0.A,5.062910e-07,NaN,CEBPB_MOUSE.H11MO.0.A,6.118130e-06,NaN
7,0_7,387,NaN,NaN,TFAP2A_MA0003.3,6.932970e-06,NaN,TFAP2A_TFAP_2,6.932970e-06,NaN,Tcfap2a.mouse_TFAP_2,1.153050e-05,NaN
8,0_8,277,NaN,NaN,TEAD3_MA0808.1,1.118060e-02,NaN,TEAD3_TEA_2,1.118060e-02,NaN,FOSL2_MA0478.1,1.118060e-02,NaN
9,0_9,263,NaN,NaN,TEAD3_MA0808.1,3.336740e-03,NaN,TEAD3_TEA_2,3.336740e-03,NaN,TEAD2_MOUSE.H11MO.0.C,3.759640e-02,NaN
10,0_10,231,NaN,NaN,ATF2_HUMAN.H11MO.0.B,6.927430e-07,NaN,ATF2_MOUSE.H11MO.0.A,6.927430e-07,NaN,FOSL2+JUNB_MA1139.1,8.413850e-06,NaN
11,0_11,167,NaN,NaN,PAX5_HUMAN.H11MO.0.A,8.396880e-01,NaN,FOS_HUMAN.H11MO.0.A,8.396880e-01,NaN,THA_HUMAN.H11MO.0.C,8.396880e-01,NaN
12,0_12,115,NaN,NaN,KLF4_MA0039.3,1.054090e-02,NaN,SALL4_HUMAN.H11MO.0.B,2.713160e-01,NaN,SALL4_MOUSE.H11MO.0.A,2.713160e-01,NaN
13,0_13,110,NaN,NaN,Tcfap2a.mouse_TFAP_1,1.826020e-03,NaN,TFAP2A_AP2_5,1.826020e-03,NaN,TFAP2C_MA0524.2,1.826020e-03,NaN
14,0_14,104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,0_15,74,NaN,NaN,ZN260_HUMAN.H11MO.0.C,2.489630e-02,NaN,OZF_HUMAN.H11MO.0.C,2.489630e-02,NaN,NFAC3_HUMAN.H11MO.0.B,1.000000e+00,NaN
16,0_16,56,NaN,NaN,CEBPA_MA0102.3,3.542960e-02,NaN,CEBPB_HUMAN.H11MO.0.A,3.542960e-02,NaN,Atf4.mouse_bZIP_1,4.784110e-02,NaN
17,0_17,50,NaN,NaN,FOS_HUMAN.H11MO.0.A,1.487240e-02,NaN,ATF3_MOUSE.H11MO.0.A,1.487240e-02,NaN,JUND_MOUSE.H11MO.0.A,1.487240e-02,NaN
18,0_18,30,NaN,NaN,NFIC+TLX1_MA0119.1,4.388190e-02,NaN,NFIA_HUMAN.H11MO.0.C,1.016710e-01,NaN,NFIA_MOUSE.H11MO.0.C,1.016710e-01,NaN
19,0_19,25,NaN,NaN,ZN121_HUMAN.H11MO.0.C,1.000000e+00,NaN,Pax2_MA0067.1,1.000000e+00,NaN,NFAC1_MOUSE.H11MO.0.A,1.000000e+00,NaN
20,0_20,20,NaN,NaN,NRF1_MOUSE.H11MO.0.A,2.008650e-05,NaN,NRF1_NRF_1,2.008650e-05,NaN,NRF1_HUMAN.H11MO.0.A,3.143850e-05,NaN
21,1_0,47,NaN,NaN,BACH1_HUMAN.H11MO.0.A,7.925380e-04,NaN,MAFF_MA0495.2,7.925380e-04,NaN,JDP2_MA0655.1,7.925380e-04,NaN
22,1_1,45,NaN,NaN,ZBT7A_HUMAN.H11MO.0.A,9.690330e-02,NaN,ZBT7A_MOUSE.H11MO.0.B,9.690330e-02,NaN,SIX4_MOUSE.H11MO.0.C,9.690330e-02,NaN
23,1_2,27,NaN,NaN,FOSL1+JUND_MA1142.1,3.354150e-04,NaN,FOSL1+JUNB_MA1137.1,3.354150e-04,NaN,FOSB+JUNB_MA1135.1,4.023170e-04,NaN

In [10]:
tomtom[0][["pattern","num_seqlets"]].to_csv(os.path.join(ppm_dir,mode+"_counts.csv"),sep=",",index=False, header=False)